### PR TITLE
Use CONDA_PREFIX in bfg launch script to find jar.

### PR DESCRIPTION
**Pull request by lebedov**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

The `bfg` shell script incorrectly used the `PREFIX` env variable (which is set to the build directory by conda-build) instead of `CONDA_PREFIX` to find the jar. This PR fixes the script.

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by carlodri** [comment]
Hi @lebedov, I'm not sure why you wanted to use `CONDA_PREFIX` here, since IIUC it points to the _path to the conda environment used to build the package_ ([docs](https://docs.conda.io/projects/conda-build/en/latest/user-guide/environment-variables.html#environment-variables-that-affect-the-build-process)), whereas here we need to know where the package will be *installed*.

However, thanks to your PR I realized that the script was not working on mac OS because the env vars were not expanded in the `bfg` script (it was not executed, only copied).

**Comment by lebedov** [comment]
I'm not sure why the online documentation is worded as it is, but `PREFIX` is only set during the build process whereas `CONDA_PREFIX` is set (by `conda activate`) to whatever conda environment is active. To confirm my assessment, run `env |grep CONDA_PREFIX` after activating an environment.

**Comment by carlodri** [comment]
oh, yes, now I see your point, sorry. I think this is the same reason for which I changed the way in which the build works in #5. However, I still don't understand why this PR fails all CIs...

**Comment by lebedov** [comment]
Not sure why CI is displeased..

**Comment by carlodri** [comment]
not sure what to do here @lebedov, if the CI does not pass there is something wrong with this. My proposal is that we merge #5 and see if it works. If it doesn't, we will get back to this PR. Do you agree? Which OSs are you working on?

**Comment by carlodri** [comment]
friendly ping @lebedov 😉

**Comment by lebedov** [comment]
Sure, assuming that `recipe/build.sh` is updated as per my comment in that PR.

**Comment by carlodri** [comment]
Actually, my proposal was to merge #5 as it is now since CI is happy there, and test if it works on your system. If not, we get back here and maybe ask for help to understand why CI fails.

**Comment by lebedov** [comment]
That PR isn't going to fix the broken `bin/bfg` on Linux problem (as of revision f200d4e) because it still is using `PREFIX` instead of `CONDA_PREFIX` in the `bin/bfg` script generated by `recipe/build.sh`.

**Comment by carlodri** [comment]
@conda-forge-admin, please rerender

**Comment by carlodri** [comment]
Closing in favour of #5, let's see if it fixes  the problem

**Pull request closed without merging**
